import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting database seed for nutri_ghar with 100% verified image URLs...');

  // 1. Seed Categories (All verified 200 OK URLs)
  const categories = [
    {
      id: 'cat-mithai',
      name: 'Mithai & Ladoo',
      slug: 'mithai',
      description: 'Traditional sweets made with pure A2 cow ghee and authentic heritage recipes.',
      image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=80',
      icon: '🍯',
      isActive: true,
    },
    {
      id: 'cat-peanut-butter',
      name: 'Peanut Butter',
      slug: 'peanut-butter',
      description: '100% stone-ground natural nut butters with zero palm oil or chemical preservatives.',
      image: 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=800&auto=format&fit=crop&q=80',
      icon: '🥜',
      isActive: true,
    },
    {
      id: 'cat-protein-nutrition',
      name: 'Protein & Nutrition',
      slug: 'protein-nutrition',
      description: 'Enriched whey and superfood blends crafted for daily vitality and fitness recovery.',
      image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=80',
      icon: '💪',
      isActive: true,
    },
    {
      id: 'cat-healthy-snacks',
      name: 'Healthy Snacks',
      slug: 'healthy-snacks',
      description: 'Slow-roasted premium nuts, crunchy seeds, and sun-dried fruit assortments.',
      image: 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=800&auto=format&fit=crop&q=80',
      icon: '🥗',
      isActive: true,
    },
  ];

  for (const cat of categories) {
    await prisma.category.upsert({
      where: { id: cat.id },
      update: cat,
      create: cat,
    });
  }
  console.log(`✓ Seeded ${categories.length} categories`);

  // 2. Seed Products (All verified 200 OK URLs)
  const products = [
    {
      id: 'besan-ladoo',
      name: 'Besan Ladoo',
      slug: 'besan-ladoo',
      categoryId: 'cat-mithai',
      categorySlug: 'mithai',
      price: 299,
      originalPrice: 349,
      image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800&auto=format&fit=crop&q=80',
      images: [
        'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=80',
      ],
      description: 'Authentic gram flour ladoos made with pure desi cow ghee and cardamom.',
      ingredients: ['Roasted Gram Flour', 'Pure A2 Cow Ghee', 'Raw Cane Sugar', 'Cardamom', 'California Almonds'],
      benefits: ['Rich in Plant Protein', 'Natural Energy Boost', 'Pure Natural Ingredients', 'Freshly Handcrafted'],
      rating: 4.8,
      reviewCount: 234,
      stockQuantity: 45,
      lowStockThreshold: 10,
      isFeatured: true,
      isBestSeller: true,
      isActive: true,
    },
    {
      id: 'dry-fruit-ladoo',
      name: 'Premium Dry Fruit Ladoo',
      slug: 'dry-fruit-ladoo',
      categoryId: 'cat-mithai',
      categorySlug: 'mithai',
      price: 449,
      originalPrice: 499,
      image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop&q=80',
      images: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop&q=80'],
      description: 'Luxurious ladoos packed with almonds, cashews, dates, and zero refined sugar.',
      ingredients: ['Almonds', 'Cashews', 'Medjool Dates', 'Pistachios', 'Pure Cow Ghee'],
      benefits: ['Rich in Antioxidants', 'Zero Refined Sugar', 'Nutrient Dense Superfood', 'Maternal Kitchen Recipe'],
      rating: 4.9,
      reviewCount: 342,
      stockQuantity: 32,
      lowStockThreshold: 8,
      isFeatured: true,
      isBestSeller: true,
      isActive: true,
    },
    {
      id: 'coconut-ladoo',
      name: 'Fresh Coconut Ladoo',
      slug: 'coconut-ladoo',
      categoryId: 'cat-mithai',
      categorySlug: 'mithai',
      price: 279,
      originalPrice: 319,
      image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=800&auto=format&fit=crop&q=80',
      images: ['https://images.unsplash.com/photo-1587314168485-3236d6710814?w=800&auto=format&fit=crop&q=80'],
      description: 'Delicate coconut ladoos made with freshly grated coconut and condensed milk solids.',
      ingredients: ['Fresh Grated Coconut', 'Condensed Milk Solids', 'Cardamom Powder', 'Ghee'],
      benefits: ['Rich in Healthy Fats', 'Delicate Soft Texture', 'Freshly Prepared', 'Festive Taste'],
      rating: 4.7,
      reviewCount: 156,
      stockQuantity: 28,
      lowStockThreshold: 10,
      isFeatured: true,
      isBestSeller: false,
      isActive: true,
    },
    {
      id: 'protein-ladoo',
      name: 'Protein Power Ladoo',
      slug: 'protein-ladoo',
      categoryId: 'cat-mithai',
      categorySlug: 'mithai',
      price: 349,
      originalPrice: 399,
      image: 'https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?w=800&auto=format&fit=crop&q=80',
      images: ['https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?w=800&auto=format&fit=crop&q=80'],
      description: 'Fitness-friendly ladoos enriched with clean whey protein isolate, roasted oats, and pure ghee.',
      ingredients: ['Whey Protein Isolate', 'Rolled Oats', 'Almonds', 'Wild Honey', 'Pure Cow Ghee'],
      benefits: ['12g Clean Protein / Piece', 'Zero White Sugar', 'Muscle Recovery Support', 'Sustained Satiety'],
      rating: 4.9,
      reviewCount: 198,
      stockQuantity: 6,
      lowStockThreshold: 10,
      isFeatured: true,
      isBestSeller: true,
      isActive: true,
    },
    {
      id: 'classic-peanut-butter',
      name: 'Pure Creamy Peanut Butter',
      slug: 'classic-peanut-butter',
      categoryId: 'cat-peanut-butter',
      categorySlug: 'peanut-butter',
      price: 249,
      originalPrice: 289,
      image: 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=800&auto=format&fit=crop&q=80',
      images: ['https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=800&auto=format&fit=crop&q=80'],
      description: '100% natural slow stone-ground peanut butter with zero additives, hydrogenated oils, or preservatives.',
      ingredients: ['Slow-Roasted Gujarat Peanuts', 'Pink Himalayan Salt', 'Organic Honey'],
      benefits: ['100% Natural Peanuts', 'No Added Palm Oil', 'High Protein Spread', 'Silky Smooth Texture'],
      rating: 4.9,
      reviewCount: 387,
      stockQuantity: 60,
      lowStockThreshold: 15,
      isFeatured: true,
      isBestSeller: true,
      isActive: true,
    },
    {
      id: 'chocolate-peanut-butter',
      name: 'Dark Chocolate Peanut Butter',
      slug: 'chocolate-peanut-butter',
      categoryId: 'cat-peanut-butter',
      categorySlug: 'peanut-butter',
      price: 329,
      originalPrice: 369,
      image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&auto=format&fit=crop&q=80',
      images: ['https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&auto=format&fit=crop&q=80'],
      description: 'Smooth slow-roasted peanut butter blended with premium dark cacao and raw honey.',
      ingredients: ['Roasted Peanuts', 'Dark Cacao (70%)', 'Raw Forest Honey', 'Himalayan Salt'],
      benefits: ['Rich in Flavonoids', 'Decadent Healthy Spread', 'Zero Refined Sugar', 'High Energy Density'],
      rating: 4.8,
      reviewCount: 267,
      stockQuantity: 40,
      lowStockThreshold: 10,
      isFeatured: true,
      isBestSeller: false,
      isActive: true,
    },
    {
      id: 'crunchy-peanut-butter',
      name: 'Crunchy Peanut Butter',
      slug: 'crunchy-peanut-butter',
      categoryId: 'cat-peanut-butter',
      categorySlug: 'peanut-butter',
      price: 279,
      originalPrice: 309,
      image: 'https://images.unsplash.com/photo-1528751014936-863e6e7a319c?w=800&auto=format&fit=crop&q=80',
      images: ['https://images.unsplash.com/photo-1528751014936-863e6e7a319c?w=800&auto=format&fit=crop&q=80'],
      description: 'Chunky stone-ground peanut butter with whole roasted peanut granules for extra crunch.',
      ingredients: ['Roasted Peanuts', 'Pink Himalayan Salt'],
      benefits: ['Satisfying Crunch', '100% Single Ingredient', 'High Dietary Fiber', 'Keto Friendly'],
      rating: 4.7,
      reviewCount: 223,
      stockQuantity: 3,
      lowStockThreshold: 10,
      isFeatured: false,
      isBestSeller: false,
      isActive: true,
    },
    {
      id: 'homemade-protein-mix',
      name: 'Homemade Protein Power Mix',
      slug: 'homemade-protein-mix',
      categoryId: 'cat-protein-nutrition',
      categorySlug: 'protein-nutrition',
      price: 399,
      originalPrice: 449,
      image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=80',
      images: ['https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=80'],
      description: 'Nutritious blend of roasted chia seeds, flaxseeds, almonds, and whole grains for complete wellness.',
      ingredients: ['Whey Protein', 'Rolled Oats', 'Almonds', 'Flaxseeds', 'Chia Seeds', 'Wild Honey'],
      benefits: ['Complete Amino Acid Profile', 'High Fiber Content', 'Post-Workout Recovery', 'Daily Family Nutrition'],
      rating: 4.8,
      reviewCount: 289,
      stockQuantity: 52,
      lowStockThreshold: 12,
      isFeatured: true,
      isBestSeller: true,
      isActive: true,
    },
    {
      id: 'high-protein-nutrition',
      name: 'Premium High Protein Mix',
      slug: 'high-protein-nutrition',
      categoryId: 'cat-protein-nutrition',
      categorySlug: 'protein-nutrition',
      price: 499,
      originalPrice: 549,
      image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&auto=format&fit=crop&q=80',
      images: ['https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&auto=format&fit=crop&q=80'],
      description: 'Advanced sports nutrition blend with 35g protein per serving for active athletes.',
      ingredients: ['Whey Isolate', 'Casein Protein', 'Almond Flour', 'Pumpkin Seeds', 'Cinnamon'],
      benefits: ['35g Protein Per Serving', 'Accelerated Recovery', 'Sustained Amino Release', 'Smooth Digestibility'],
      rating: 4.9,
      reviewCount: 312,
      stockQuantity: 38,
      lowStockThreshold: 10,
      isFeatured: true,
      isBestSeller: false,
      isActive: true,
    },
    {
      id: 'roasted-healthy-mix',
      name: 'Roasted Healthy Nuts Mix',
      slug: 'roasted-healthy-mix',
      categoryId: 'cat-healthy-snacks',
      categorySlug: 'healthy-snacks',
      price: 229,
      originalPrice: 259,
      image: 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=800&auto=format&fit=crop&q=80',
      images: ['https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=800&auto=format&fit=crop&q=80'],
      description: 'Lightly roasted and seasoned mix of premium California almonds, cashews, and sunflower seeds.',
      ingredients: ['Almonds', 'Cashews', 'Peanuts', 'Sunflower Seeds', 'Sea Salt'],
      benefits: ['Heart-Healthy Fats', 'Crunchy Guilt-Free Snack', 'Zero Trans Fats', 'Rich in Vitamin E'],
      rating: 4.7,
      reviewCount: 178,
      stockQuantity: 44,
      lowStockThreshold: 10,
      isFeatured: false,
      isBestSeller: false,
      isActive: true,
    },
    {
      id: 'protein-energy-bites',
      name: 'Protein Energy Bites',
      slug: 'protein-energy-bites',
      categoryId: 'cat-healthy-snacks',
      categorySlug: 'healthy-snacks',
      price: 279,
      originalPrice: 319,
      image: 'https://images.unsplash.com/photo-1514733670139-4d87a1941d55?w=800&auto=format&fit=crop&q=80',
      images: ['https://images.unsplash.com/photo-1514733670139-4d87a1941d55?w=800&auto=format&fit=crop&q=80'],
      description: 'Bite-sized energy balls packed with dates, roasted nuts, seeds, and natural sweetness.',
      ingredients: ['Dates', 'Roasted Almonds', 'Pumpkin Seeds', 'Dark Chocolate Chips', 'Honey'],
      benefits: ['On-the-go Pre-Workout Snack', 'Natural Electrolytes', 'No Preservatives', 'Clean Calorie Source'],
      rating: 4.8,
      reviewCount: 234,
      stockQuantity: 25,
      lowStockThreshold: 8,
      isFeatured: true,
      isBestSeller: true,
      isActive: true,
    },
    {
      id: 'dry-fruit-mix',
      name: 'Premium Dry Fruit Assortment',
      slug: 'dry-fruit-mix',
      categoryId: 'cat-healthy-snacks',
      categorySlug: 'healthy-snacks',
      price: 599,
      originalPrice: 649,
      image: 'https://images.unsplash.com/photo-1596591606975-97ee5cef3a1e?w=800&auto=format&fit=crop&q=80',
      images: ['https://images.unsplash.com/photo-1596591606975-97ee5cef3a1e?w=800&auto=format&fit=crop&q=80'],
      description: 'Royal selection of jumbo almonds, Afghani cashews, Chilean walnuts, and golden raisins.',
      ingredients: ['California Almonds', 'Goan Cashews', 'Walnuts', 'Golden Raisins', 'Black Currants'],
      benefits: ['Superfood Antioxidants', 'Brain Health & Vitality', 'Long Natural Shelf Life', 'Gift Grade Quality'],
      rating: 4.9,
      reviewCount: 298,
      stockQuantity: 30,
      lowStockThreshold: 10,
      isFeatured: true,
      isBestSeller: true,
      isActive: true,
    },
  ];

  for (const prod of products) {
    await prisma.product.upsert({
      where: { id: prod.id },
      update: prod,
      create: prod,
    });
  }
  console.log(`✓ Seeded ${products.length} products with verified active URLs`);

  // 3. Seed Website Content
  const contents = [
    {
      id: 'content-hero',
      section: 'hero',
      data: {
        eyebrow: 'HOMEMADE WELLNESS',
        headline: 'Goodness That',
        headlineItalic: 'Feels Like Home.',
        supportingText: 'Naturally made foods and nutrition products crafted with care for your everyday wellness. Pure A2 ghee, stone-ground nuts, and authentic home-style craft.',
        primaryButtonText: 'Shop Bestsellers',
        secondaryButtonText: 'Explore Collections',
        heroImage: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=1200&auto=format&fit=crop&q=80',
      },
    },
    {
      id: 'content-announcement',
      section: 'announcement',
      data: {
        enabled: true,
        text: '🌿 100% Pure Nutri Ghar Nutrition • Homemade With Purity & Traditional Care',
      },
    },
    {
      id: 'content-brand-story',
      section: 'brand_story',
      data: {
        eyebrow: 'THE NUTRI GHAR WAY',
        heading: 'Rooted in Tradition.',
        headingItalic: 'Made for Today.',
        paragraph1: 'At Nutri Ghar, we believe you shouldn’t have to choose between the pure, heartwarming flavors of Indian heritage and the clean nutritional standards demanded by modern living.',
        paragraph2: 'Every jar of stone-ground peanut butter and every handcrafted batch of ladoos begins with 100% whole ingredients: pure A2 desi cow ghee, California almonds, rich roasted gram flour, and wild forest honey.',
        paragraph3: 'No industrial shortcuts. Zero palm oil, no artificial flavorings, and no chemical preservatives. Just honest, wholesome nutrition prepared exactly the way it would be in your family home.',
        storyImage: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=1000&auto=format&fit=crop&q=80',
        quote: '“Food made with the warmth of a mother’s kitchen nourishes not just the body, but the soul.”',
      },
    },
    {
      id: 'content-contact',
      section: 'contact',
      data: {
        phone: '+91 98765 43210',
        email: 'care@nutrighar.com',
        whatsapp: '+91 98765 43210',
        address: 'Nutri Ghar Artisanal Kitchen, Sector 14, Gurugram, Haryana - 122001',
        fssaiLicense: 'FSSAI Lic: 10823005000214',
      },
    },
    {
      id: 'content-footer',
      section: 'footer',
      data: {
        aboutText: 'Nutri Ghar represents healthy food made with the warmth and trust of home. Small batches crafted with pure ingredients, zero chemical preservatives, and traditional recipes.',
        instagramUrl: 'https://instagram.com',
        whatsappUrl: 'https://wa.me/919876543210',
        facebookUrl: 'https://facebook.com',
        copyrightText: `© ${new Date().getFullYear()} Nutri Ghar. Pure homemade nutrition crafted with care.`,
      },
    },
    {
      id: 'content-newsletter',
      section: 'newsletter',
      data: {
        heading: 'A Little Goodness in Your Inbox.',
        description: 'Receive thoughtful wellness notes, seasonal kitchen recipes, and priority access to fresh batches.',
        promoNote: 'We respect your privacy. No spam, ever. Unsubscribe anytime.',
      },
    },
  ];

  for (const item of contents) {
    await prisma.websiteContent.upsert({
      where: { section: item.section },
      update: { data: item.data },
      create: { id: item.id, section: item.section, data: item.data },
    });
  }
  console.log(`✓ Seeded ${contents.length} website content sections`);

  // 4. Seed Admin User
  await prisma.adminUser.upsert({
    where: { email: 'admin@nutrighar.com' },
    update: {
      username: 'admin',
      name: 'Store Administrator',
      role: 'admin',
    },
    create: {
      id: 'admin-1',
      username: 'admin',
      email: 'admin@nutrighar.com',
      passwordHash: 'NutriGhar@2026',
      name: 'Store Administrator',
      role: 'admin',
    },
  });
  console.log('✓ Seeded default admin user (admin@nutrighar.com / NutriGhar@2026)');

  console.log('✨ PostgreSQL database seeding completed with 100% active images!');
}

main()
  .catch((e) => {
    console.error('Error during seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
